import { CSVProjectRow, ProjectSection, MediaItem } from '@/types/projects';

export const csvParser = {
  /**
   * Parse CSV string to project structure
   */
  parseProjectCSV(csvString: string): ProjectSection[] {
    const lines = csvString.trim().split('\n');
    
    if (lines.length < 2) {
      throw new Error('CSV must contain header and at least one data row');
    }

    // Parse header
    const header = this.parseCSVLine(lines[0]);
    const expectedHeaders = [
      'section_order',
      'section_title',
      'section_content',
      'image_url_1',
      'image_url_2',
      'image_url_3',
      'video_url',
      'video_type',
    ];

    // Validate headers
    const hasRequiredHeaders = expectedHeaders
      .slice(0, 3)
      .every((h) => header.includes(h));

    if (!hasRequiredHeaders) {
      throw new Error(
        'CSV must contain required headers: section_order, section_title, section_content'
      );
    }

    // Parse data rows
    const sections: ProjectSection[] = [];
    
    for (let i = 1; i < lines.length; i++) {
      const line = lines[i].trim();
      if (!line) continue;

      try {
        const values = this.parseCSVLine(line);
        const row: any = {};

        header.forEach((key, index) => {
          row[key] = values[index] || '';
        });

        const section = this.rowToSection(row, i);
        sections.push(section);
      } catch (error: any) {
        console.error(`Error parsing line ${i + 1}:`, error.message);
      }
    }

    if (sections.length === 0) {
      throw new Error('No valid sections found in CSV');
    }

    return sections;
  },

  /**
   * Validate CSV format
   */
  validateCSV(csvString: string): { valid: boolean; errors: string[] } {
    const errors: string[] = [];

    try {
      const lines = csvString.trim().split('\n');

      if (lines.length < 2) {
        errors.push('CSV must contain header and at least one data row');
        return { valid: false, errors };
      }

      // Check header
      const header = this.parseCSVLine(lines[0]);
      const requiredHeaders = ['section_order', 'section_title', 'section_content'];

      for (const required of requiredHeaders) {
        if (!header.includes(required)) {
          errors.push(`Missing required header: ${required}`);
        }
      }

      // Check data rows
      for (let i = 1; i < lines.length; i++) {
        const line = lines[i].trim();
        if (!line) continue;

        const values = this.parseCSVLine(line);

        if (values.length < 3) {
          errors.push(`Line ${i + 1}: Missing required fields`);
        }

        const order = parseInt(values[0]);
        if (isNaN(order) || order < 1) {
          errors.push(`Line ${i + 1}: Invalid section_order`);
        }

        if (!values[1] || values[1].length < 3) {
          errors.push(`Line ${i + 1}: section_title is too short`);
        }

        if (!values[2] || values[2].length < 10) {
          errors.push(`Line ${i + 1}: section_content is too short`);
        }
      }
    } catch (error: any) {
      errors.push(`CSV parsing error: ${error.message}`);
    }

    return {
      valid: errors.length === 0,
      errors,
    };
  },

  /**
   * Convert CSV row to ProjectSection
   */
  private rowToSection(row: CSVProjectRow, index: number): ProjectSection {
    const order = parseInt(row.section_order);
    
    if (isNaN(order)) {
      throw new Error(`Invalid section order: ${row.section_order}`);
    }

    const media: MediaItem[] = [];

    // Add images
    if (row.image_url_1) {
      media.push({
        type: 'image',
        url: row.image_url_1.trim(),
      });
    }
    if (row.image_url_2) {
      media.push({
        type: 'image',
        url: row.image_url_2.trim(),
      });
    }
    if (row.image_url_3) {
      media.push({
        type: 'image',
        url: row.image_url_3.trim(),
      });
    }

    // Add video
    if (row.video_url) {
      const videoType = row.video_type || 'youtube';
      media.push({
        type: 'video-embed',
        url: row.video_url.trim(),
        platform: videoType as any,
      });
    }

    return {
      // Don't include id - it will be generated by database
      projectId: '', // Will be set when project is created
      order,
      title: row.section_title.trim(),
      content: row.section_content.trim(),
      media,
    } as ProjectSection;
  },

  /**
   * Parse a CSV line, handling quoted values
   */
  private parseCSVLine(line: string): string[] {
    const values: string[] = [];
    let currentValue = '';
    let inQuotes = false;

    for (let i = 0; i < line.length; i++) {
      const char = line[i];

      if (char === '"') {
        if (inQuotes && line[i + 1] === '"') {
          // Escaped quote
          currentValue += '"';
          i++;
        } else {
          // Toggle quote mode
          inQuotes = !inQuotes;
        }
      } else if (char === ',' && !inQuotes) {
        // End of field
        values.push(currentValue);
        currentValue = '';
      } else {
        currentValue += char;
      }
    }

    // Add last value
    values.push(currentValue);

    return values.map((v) => v.trim());
  },

  /**
   * Generate sample CSV template
   */
  generateTemplate(): string {
    return `section_order,section_title,section_content,image_url_1,image_url_2,image_url_3,video_url,video_type
1,Introduction,"This is the introduction to my project. Describe what you'll be building and why.",https://example.com/image1.jpg,,,https://youtube.com/embed/abc123,youtube
2,Materials Needed,"List all materials and tools needed for the project.",https://example.com/materials.jpg,https://example.com/tools.jpg,,,
3,Step 1 - Assembly,"Detailed instructions for the first step of assembly.",https://example.com/step1.jpg,,,,
4,Step 2 - Wiring,"Connect all the wires according to the diagram.",https://example.com/wiring.jpg,,,https://youtube.com/embed/def456,youtube
5,Conclusion,"Summary of the project and final thoughts.",,,,,,`;
  },
};
